### ISSUE TITLE
Implement Claim Checks into the FlowNodeInstanceService

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/process_engine#112]
#### Describe your issue

Currently, claim checks are only performed in the `ProcessModelService`. These cover most relevant functionalities, but we also need claim checks in the `FlowNodeInstanceService` to cover access right checks for Flow-Node specific queries.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
https://github.com/process-engine-pro/organization/issues/175

**Comment by 5ebastianMeier** [comment]
@cmg-dev @roblen45
For this to be implemented we should first talk about which claims we want to check here.

I'd suggest to just use an atomic claim operation on the `FlowNodeInstanceRepository` a la `canRead${object}` before calling it from the `FlowNodeInstanceService`.

**Comment by 5ebastianMeier** [comment]
I've talked to @roblen45 about this and we came to the conclusion that claims don't make sense on this level, because there is no feature context.

This would result in a too complex configuration setup for the Identity Server.
