### ISSUE TITLE
Implement Message Catch-/Throw-Event and SendTask

### ISSUE THREAD

**Issue by 5ebastianMeier** [process-engine/process_engine#125]
#### Describe your issue

We currently only have an empty behavior so that there are no runtime errors when a Catch- or Throw-Event is reached. The implementation for any kinds of events are still missing though.

The first we should implement is the Message Catch- and Throw-Event.

The SendTask is expected to have a message type configured on to it using BPMN-Studio.
It should send a message and wait for a response, so that a synchronous execution can be modeled. 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
https://github.com/process-engine-pro/organization/issues/182
