### ISSUE TITLE
🐛Processes with same task id are finished together

### ISSUE THREAD

**Issue by dominikkaminski** [process-engine/process_engine#148]
#### Describe your issue

When you have two tasks (with user task nodes) with the same `task id` but different `process model id` then they will finish both although you only submitted one.

#### How can others reproduce the issue?

Create two tasks (with user task nodes) with same `task id` but different `process model id`.
Then continue one process.

1. Create a **new** executeable diagram.
2. Add a **user task** to diagram.
3. Click **publish**.
4. Navigate to process engine view
5. Click **run**
6. When user task input view is displayed, click **abort**.
7. Open the **same** diagram in process engine view **again**
8. Click **run**
9. When user task input view is displayed, click **abort**.
10. Navigate to **inspect** view.
-> Now there should be **two waiting** user tasks.
11. Select one and **continue** it.
12. Click **Finish**
13. Navigate to **inspect** view.
-> Now there should be one user task left, but according to this bug, **both are finished**

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
@dominikkaminski Do I understand you right, you are creating two diagrams and in each you are creating a user task that have the same id?

**Comment by ElRaptorus** [comment]
@dominikkaminski Do you have a bpmn diagram for this?

**Comment by dominikkaminski** [comment]
@Vyperus , @ElRaptorus 
Please follow this guide:

1. Create a **new** executeable diagram.
2. Add a **user task** to diagram.
3. Click **publish**.
4. Navigate to process engine view
5. Click **run**
6. When user task input view is displayed, click **abort**.
7. Open the **same** diagram in process engine view **again**
8. Click **run**
9. When user task input view is displayed, click **abort**.
10. Navigate to **inspect** view.
-> Now there should be **two waiting** user tasks.
11. Select one and **continue** it.
12. Click **Finish**
13. Navigate to **inspect** view.
-> Now there should be one user task left, but according to this bug, **both are finished**

Also approved in database.

**Comment by ElRaptorus** [comment]
I can confirm this now. 
This is an issue with the events the process engine and consumer api use to communicate with each other.
I'll fix this asap. Shouldn't take long.

**Comment by ElRaptorus** [comment]
@dominikkaminski FYI:
We decided to pool all issues in the [ProcessEngine-Runtime](https://github.com/process-engine/process_engine_runtime) repository. 
I moved this issue [there](https://github.com/process-engine/process_engine_runtime/issues/25).
