### ISSUE TITLE
Delegate execution if necessary on continueOwnProcesses

### ISSUE THREAD

**Issue by heikomat** [process-engine/process_engine#2]
When the process-engine starts up, it checks if there are any waiting processes, that need to be continued (for example if when the process-engine restarted).

When this happens, it checks all waiting processes. it currently just continues the execution on its own, if no other process-engine-instance claims responsibility for that process.

Here we need to check if we actually have the necessary features to continue the execution. If not, the execution needs to be delegated.

**Comment by ElRaptorus** [comment]
As of v14.0.0., this function does not exist anymore.
