### ISSUE TITLE
🐛 Usertasks have no access at all to the token-history

### ISSUE THREAD

**Issue by heikomat** [process-engine/process_engine#47]
#### Describe your issue

Usertasks have no access at all to the token-history.

This was working before, but broke in #38. [here](https://github.com/process-engine/process_engine/pull/38/files#diff-b56e67680ec1cb43d023c1049e5e07ddR70) to be exact.

#### How can others reproduce the issue?

Accessing `token.history` in a userTask-ui-config won't work

#### Possible solution

Don't remove the token-history before sending it to the browser.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ppoetschke** [comment]
Please do not reverse this bug!!! The former behavior led to a serious performance issue and a memory leak.
It is intended that usertasks do not have access to the token history by default. If it's wanted to use history data, they have to be explicitly mapped in the userConfig or userData.

**Comment by cmg-dev** [comment]
https://github.com/process-engine-pro/organization/issues/43
