### ISSUE TITLE
Parallel Join Gateways do not Return the Correct Token History

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/process_engine#48]
#### Describe your issue

When running a process that includes two or more parallel running tasks and a parallel join gateway at the end, the process result will only include the result of the task that was finished last. 

It would make more sense, if the values of *all* the parallel running tasks would be included in the history token of the parallel join gateway.

#### How can others reproduce the issue?

- Create a process with 2 or more tasks that run in parallel
- Let Task 1 run, say, 1 second and return the value "A"
- Let Task 2 run 3 seconds and return the value "B"
- After the parallel join gateway has finished, the value for `token.current` will only be `B`
    - Expected value would be: `{ Task1: 'A', Task2: 'B' }`

You can also use the existing [Sample](https://github.com/process-engine/example_processes/tree/feature/add_parallel_gateway/ParallelGateway) to verify this.

#### Possible solution

A possible workaround would be creating a mapper on the parallel join gateway, which includes the task results of each parallel running task.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
https://github.com/process-engine-pro/organization/issues/43

**Comment by ppoetschke** [comment]
Please check if this could be already solved with this open PR: https://github.com/process-engine/process_engine/pull/40

**Comment by ppoetschke** [comment]
I don't think it's a good idea to change the standard behavior of the process engine in this special case. The current token is always meant to be the last token arriving at this task. Accessing token data of specific tasks should always be done over the token history. We should take care that the token history is merged correctly at the parallel join gateway, this should solve this problem.

**Comment by ElRaptorus** [comment]
But isn't the parallel join gateway a special case by it's very definition? 
The very purpose of that gateway is to handle the execution of multiple tasks. So why should the resulting current token not consist of all the task results? 
If I have a follow up task after a parallel join gateway, which requires the results of these tasks (and nothing more), I think it is reasonable to be able to retrieve these results by using `token.current`.

Also, I think using token.history isn't a good idea for this either because that would also provide the task with loads of data it doesn't have any interest in, which might get unnecessarily bulky, if I have a process model with 100+ tasks in it. 

As an analogy, I'm thinking of a `Promise.all()` scenario, the result of which always contains the results of each promise that was run, but nothing more (and more importantly nothing less).
/cc @5ebastianMeier @cmg-dev

**Comment by ppoetschke** [comment]
Good points, at the end this isn't only a bug or an issue. This has to be discussed and decided at a conceptual layer. Please open an issue at the appropriate place.

Some remarks, the purpose of a parallel join gateway is not executing multiple tasks, it's merging the incoming flows and therefore the arriving tokens. It doesn't execute something. Also, the token history is anyway present as part of the token object and it makes no difference, if we use `token.history.task1` or `token.current.task1`, but the last one could violate a basic pattern of token structure.
`Promise.all()` is also not a good comparison, because we're talking mainly about a clean process logic, not about a technical implementation.

**Comment by ElRaptorus** [comment]
This is fixed now.
