### ISSUE TITLE
parallel gateways do not create individual tokens for each parallel execution path

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/process_engine#49]
#### Describe your issue

When creating a process which has two or more parallel running execution paths, they all use a common token. 

This means, that the tasks located in the execution paths will very likely get wrong values when accessing `token.current`.

#### How can others reproduce the issue?

- Create a process with 2 parallel execution paths
- Create 1 Task in the first execution path:
    - It should delay for 1 second and return a random value that can be used for `token.current`
- Create 2 Tasks in the second execution path: 
    - Task 1 only returns a dummy value without delay (so that it finishes before the task in execution path 1)
    - Insert a timing event that waits for 2 seconds
    - Task 2 (which must run *after* the timer finishes) receives `token.current` as parameter and prints it out
    - You will then notice, that the value for `token.current` is equal to the value returned by the task in execution path 1

You can also use the existing [Sample](https://github.com/process-engine/example_processes/tree/feature/add_parallel_gateway/ParallelGateway) to verify this.

#### Possible solution

Each parallel execution path must get its own token.
Until this is done, such scenarios should not be using `token.current` altogether.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
https://github.com/process-engine-pro/organization/issues/43

**Comment by ppoetschke** [comment]
Please check if this could be already solved with this open PR: https://github.com/process-engine/process_engine/pull/40
