### ISSUE TITLE
Race Condition When Using Boundary Events And Script Tasks

### ISSUE THREAD

**Issue by Paulomart** [process-engine/process_engine#56]
#### Describe your issue

Using [this bpmn diagram](https://github.com/process-engine/process_engine/files/1906494/test_error_boundary_event.txt) fails.

An `UnhandledPromiseRejectionWarning` is thrown:
```
(node:70343) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): error: duplicate key value violates unique constraint "ScriptTask_pkey"
(node:70343) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Setup:**
- Use a `ScriptTask`
- Attach an interrupting `BoundaryEvent`
- Let the `ScriptTask` throw an error

**Error Description**
- Having an interrupting boundary event will indirectly cause the script task to `end` if an error is thrown
- The script task also `end`s on its own in a regular fashion
- Both `end` calls will cause a `ScriptTask#save(...)` call. This race condition causes the second save to fail.

1. **First Path to `save()`**
    - `ScriptTask#error(...)` gets called
      https://github.com/process-engine/process_engine/blob/301602f3066515eea0cb90ddb458c5e4eb9dd476/src/entity_types/script_task.ts#L45-L51

    - `ScriptTask#triggerEvent()` gets called
      https://github.com/process-engine/process_engine/blob/301602f3066515eea0cb90ddb458c5e4eb9dd476/src/entity_types/node_instance.ts#L290-L293

    - Error Event gets published on the event aggregator
      https://github.com/process-engine/process_engine/blob/301602f3066515eea0cb90ddb458c5e4eb9dd476/src/entity_types/node_instance.ts#L328

    - In `NodeInstanceEntityTypeService` the Event gets processed: `ScriptTask#event(...)` will be called
      https://github.com/process-engine/process_engine/blob/301602f3066515eea0cb90ddb458c5e4eb9dd476/src/entity_type_services/node_instance.ts#L146-L150

    - In `ScriptTask` `boundaryEvent()` gets called.
      https://github.com/process-engine/process_engine/blob/301602f3066515eea0cb90ddb458c5e4eb9dd476/src/entity_types/node_instance.ts#L376-L381

    - In `boundaryEvent(...)` `ScriptTask#end` gets called
      https://github.com/process-engine/process_engine/blob/301602f3066515eea0cb90ddb458c5e4eb9dd476/src/entity_types/node_instance.ts#L432-L450

    - In `ScriptTask#end` `ScriptTask#save(...)` gets called
      https://github.com/process-engine/process_engine/blob/301602f3066515eea0cb90ddb458c5e4eb9dd476/src/entity_types/node_instance.ts#L639

2. **Second Path to `save()`**
    - After the `try/catch` `ScriptTask#changeState('end')` gets called
      https://github.com/process-engine/process_engine/blob/301602f3066515eea0cb90ddb458c5e4eb9dd476/src/entity_types/script_task.ts#L65
        
    - The EndEvent is published via the EventAggregator
      https://github.com/process-engine/process_engine/blob/301602f3066515eea0cb90ddb458c5e4eb9dd476/src/entity_types/node_instance.ts#L287

    - In `NodeInstanceEntityTypeService` the EndEvent gets processed: `ScriptTask#end(...)` will be called
      https://github.com/process-engine/process_engine/blob/301602f3066515eea0cb90ddb458c5e4eb9dd476/src/entity_type_services/node_instance.ts#L122-L124

    - In `ScriptTask#end` `ScriptTask#save(...)` gets called
      https://github.com/process-engine/process_engine/blob/301602f3066515eea0cb90ddb458c5e4eb9dd476/src/entity_types/node_instance.ts#L639

#### How can others reproduce the issue?

Just try the bpmn diagram above.

#### Possible solution

Adapt the behaivor of the `ServiceTask` to the `ScriptTask`

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by heikomat** [comment]
- Having an interrupting boundary event will cause the script task to `end` if an error is thrown
- The script task also `end`s on its own
- both `end` calls will cause a `save` call

The service task circumvents this by not causing the task to end on its own, if an error is thrown

**Comment by heikomat** [comment]
The ServiceTask circumvents this problem by not calling the regular `end` if an error is thrown
