### ISSUE TITLE
ErrorBoundary Event - Default Properties of the token object will deleted

### ISSUE THREAD

**Issue by robpal94** [process-engine/process_engine#71]
#### Describe your issue
Consider the given process [error_boundary_test.txt](https://github.com/process-engine/process_engine/files/1950598/error_boundary_test.txt) .

If the token passes the `Throw no Error` task, the complete object structure of the token object gets replaced. 

In the normal case, the token object has a structure, which looks like: 
```
{
    current: {}, 
    history: {}
}
``` 

After the excecution of the Script Taskt, with the given Error boundary Event, the Token Object Structure looks like this:
```
{
    message: "",
    errorCode: ""
}
```

This Bug prevents the further access on the default token properties, such as `history`, and should not occur. 

#### How can others reproduce the issue?
* Create a Task
* Attach a `ErrorBoundaryEvent` to it
* Write a script task, that simply `console.log()` the token object (or any task, that tries to access the default token properties). 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
Checking the log output of the attached process, I discoverd that the ErrorBoundaryEvent gets called, even though it shouldn't. 
This might not be directly related to t
<img width="1394" alt="bildschirmfoto 2018-04-30 um 10 05 18" src="https://user-images.githubusercontent.com/15343316/39419083-5464af30-4c5e-11e8-9cf7-034afea18ab4.png">
he token issue, but it clearly shows that there is more going on here than it should be.
/cc @5ebastianMeier

**Comment by ElRaptorus** [comment]
After doing some in-depth tests for this, I am certain that the token handling seems to be correct.
I added some `console.log()` statement to the individual script tasks of the process and as you can see, the token structure remains consistent. 
Maybe this issue was fixed coincidentally by another PR. 

I'll leave this open for now, in case we stumble upon this issue again, but for now this is not reproducable.

**Comment by ElRaptorus** [comment]
https://github.com/process-engine-pro/organization/issues/72
