### ISSUE TITLE
 Call to processEngineService.executeProcess does not reject if bpmn references unknown module

### ISSUE THREAD

**Issue by stheuer** [process-engine/process_engine#80]
Calling processEngineService.executeProcess does not reject with invalid bpmn process if misconfiguration is wrong module reference.

#### Describe your issue
If a bpmn process runs a service task that references a component that is not registered at the ioc container, calling this process with processEngineService.executeProcess does not reject but gives a error log info only (" Error: registration for key "UnknownServiceName" not found")

#### How can others reproduce the issue?
1) Create A bpmn process file that executes a ServiceTask.
2 Reference a module with name ''UnknownModule" in that Service Task with method "unknownMethod" and params []

3) Run a Programm that bootsraps the process engine and executes the bpmn proces with

processEngineService.executeProcess(executionContext, undefined, PROCESS_KEY, {})
.catch(() => {console.log('No issue')});

#### What's your setup

- OS Windows 7
- Node (`node --version`):
- NPM v8.9.0

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [ ] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
As of v14.0.0, this function does not exist anymore.
