### ISSUE TITLE
Call Activity - Cannot read property id of undefined when trying to execute a call activity that calls another call activity

### ISSUE THREAD

**Issue by robpal94** [process-engine/process_engine#85]
#### Describe your issue
Consider the following process:

![samle](https://user-images.githubusercontent.com/38498731/39994033-4e7dc488-5778-11e8-9726-e99420a16192.png)

Here, the call activity should call another call activity. 

When I execute the process, I get the following stack trace: 
```
(node:7141) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined
    at SubprocessExternalEntity.execute (/Users/robin/Documents/process_engine/process_engine_meta/_integration_tests/node_modules/@process-engine/process_engine/dist/commonjs/entity_types/subprocess_external.js:38:55)
    at <anonymous>
(node:7141) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7141) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

#### How can others reproduce the issue?
Execute [this process](https://github.com/process-engine/process_engine/files/2000404/sample_process.txt)

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
I think the implementation of the consumer api solves this.
Please check if this is still an issue, after this PR gets merged:
https://github.com/process-engine/process_engine/pull/90
